esp8266:
  board: esp01_1m
  framework:
    platform_version: 4.2.1

uart:
  id: ecodan_uart
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3
  rx_buffer_size: 1024
  parity: EVEN

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
